eslint:
    enabled: true
    config:
        extensions:
            - .es6
            - .ts
            - .mjs
exclude_patterns:
  - ".circleci/"
  - ".yarn/"
  - "node_modules/"
  - "scripts/"
  - "tests/"
  - "dist/"
  - "src/types"
